// auto-generated by x2java xpiler

package x2;

import java.io.IOException;
import java.util.*;

import x2.*;
import x2.util.*;

public final class BuiltinEventType {
    private BuiltinEventType() { }

    public static final int HeartbeatEvent = -1;
    public static final int FlowStart = -2;
    public static final int FlowStop = -3;
    public static final int TimeoutEvent = -4;
}
