// auto-generated by x2java xpiler

package x2;

import java.io.IOException;
import java.util.*;

import x2.*;
import x2.util.*;

public class HeartbeatEvent extends Event {
    protected static Tag tag;

    static {
        tag = new Tag(Event.tag, HeartbeatEvent.class, 0, BuiltinEventType.HeartbeatEvent);
    }

    public HeartbeatEvent() {
        super(tag.getNumProps());
        init();
    }

    protected HeartbeatEvent(int length) {
        super(length + tag.getNumProps());
        init();
    }

    private void init() {
    }

    @Override
    protected boolean equalsTo(Cell other) {
        if (!super.equalsTo(other)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode(Fingerprint fingerprint) {
        return super.hashCode(fingerprint);
    }

    @Override
    protected boolean isEquivalent(Cell other, Fingerprint fingerprint) {
        if (!super.isEquivalent(other, fingerprint)) {
            return false;
        }
        return true;
    }

    @Override
    public Cell.Tag _getTypeTag() { return tag; }

    @Override
    public int _getTypeId() { return tag.getTypeId(); }

    @Override
    protected void describe(StringBuilder sb) {
        super.describe(sb);
    }

    // Serialization

    @Override
    public void deserialize(Deserializer deserializer) throws IOException {
        super.deserialize(deserializer);
    }

    @Override
    public int length() {
        int length = super.length();
        return length;
    }

    @Override
    public void serialize(Serializer serializer) {
        super.serialize(serializer);
    }
}
