// auto-generated by x2java xpiler

package x2;

import java.io.IOException;
import java.util.*;

import x2.*;
import x2.util.*;

public class HandshakeReq extends Event {
    protected static Tag tag;

    private byte[] data_;

    public byte[] getData() {
        return data_;
    }
    public HandshakeReq setData(byte[] value) {
        data_ = value;
        return this;
    }

    static {
        tag = new Tag(Event.tag, HandshakeReq.class, 1, LinkEventType.HandshakeReq);
    }

    public HandshakeReq() {
        super(tag.getNumProps());
        init();
    }

    protected HandshakeReq(int length) {
        super(length + tag.getNumProps());
        init();
    }

    private void init() {
        data_ = null;
    }

    @Override
    protected boolean equalsTo(Cell other) {
        if (!super.equalsTo(other)) {
            return false;
        }
        HandshakeReq o = (HandshakeReq)other;
        if (data_ != o.data_) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode(Fingerprint fingerprint) {
        Hash hash = new Hash(super.hashCode(fingerprint));
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            hash.update(data_);
        }
        return hash.code();
    }

    @Override
    protected boolean isEquivalent(Cell other, Fingerprint fingerprint) {
        if (!super.isEquivalent(other, fingerprint)) {
            return false;
        }
        HandshakeReq o = (HandshakeReq)other;
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            if (data_ != o.data_) {
                return false;
            }
        }
        return true;
    }

    @Override
    public Cell.Tag _getTypeTag() { return tag; }

    @Override
    public int _getTypeId() { return tag.getTypeId(); }

    @Override
    protected void describe(StringBuilder sb) {
        super.describe(sb);
        sb.append(" Data: ");
        sb.append(data_);
    }

    // Serialization

    @Override
    public void deserialize(Deserializer deserializer) throws IOException {
        super.deserialize(deserializer);
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            data_ = deserializer.readBytes();
        }
    }

    @Override
    public int length() {
        int length = super.length();
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            length += Serializer.lengthBytes(data_);
        }
        return length;
    }

    @Override
    public void serialize(Serializer serializer) {
        super.serialize(serializer);
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            serializer.writeBytes(data_);
        }
    }
}
