// auto-generated by x2java xpiler

package x2;

import java.io.IOException;
import java.util.*;

import x2.*;
import x2.util.*;

public final class LinkEventType {
    private LinkEventType() { }

    public static final int LinkSessionConnected = -10;
    public static final int LinkSessionDisconnected = -11;
    public static final int HandshakeReq = -12;
    public static final int HandshakeResp = -13;
    public static final int HandshakeAck = -14;
}
