// auto-generated by x2java xpiler

package x2samples;

import java.io.IOException;
import java.util.*;

import x2java.*;
import x2java.util.*;

public class HelloResp extends Event {
    protected static Tag tag;

    private String greeting_;

    public String getGreeting() {
        return greeting_;
    }
    public HelloResp setGreeting(String value) {
        fingerprint.touch(tag.getOffset() + 0);
        greeting_ = value;
        return this;
    }

    static {
        tag = new Tag(Event.tag, HelloResp.class, 1, 2);
    }

    public HelloResp() {
        super(tag.getNumProps());
        init();
    }

    protected HelloResp(int length) {
        super(length + tag.getNumProps());
        init();
    }

    private void init() {
        greeting_ = "";
    }

    @Override
    protected boolean equalsTo(Cell other) {
        if (!super.equalsTo(other)) {
            return false;
        }
        HelloResp o = (HelloResp)other;
        if (greeting_ != o.greeting_) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode(Fingerprint fingerprint) {
        Hash hash = new Hash(super.hashCode(fingerprint));
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            hash.update(greeting_);
        }
        return hash.code();
    }

    @Override
    protected boolean isEquivalent(Cell other, Fingerprint fingerprint) {
        if (!super.isEquivalent(other, fingerprint)) {
            return false;
        }
        HelloResp o = (HelloResp)other;
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            if (greeting_ != o.greeting_) {
                return false;
            }
        }
        return true;
    }

    @Override
    public Cell.Tag _getTypeTag() { return tag; }

    @Override
    public int _getTypeId() { return tag.getTypeId(); }

    @Override
    protected void describe(StringBuilder sb) {
        super.describe(sb);
        sb.append(" Greeting: ");
        sb.append(greeting_);
    }

    // Serialization

    @Override
    public void deserialize(Deserializer deserializer) throws IOException {
        super.deserialize(deserializer);
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            greeting_ = deserializer.readString();
        }
    }

    @Override
    public int length() {
        int length = super.length();
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            length += Serializer.lengthString(greeting_);
        }
        return length;
    }

    @Override
    public void serialize(Serializer serializer) {
        super.serialize(serializer);
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            serializer.writeString(greeting_);
        }
    }
}
