// auto-generated by x2java xpiler

package x2java;

import java.io.IOException;
import java.util.*;

import x2java.*;
import x2java.util.*;

public class HandshakeAck extends Event {
    protected static Tag tag;

    private boolean result_;

    public boolean getResult() {
        return result_;
    }
    public HandshakeAck setResult(boolean value) {
        fingerprint.touch(tag.getOffset() + 0);
        result_ = value;
        return this;
    }

    static {
        tag = new Tag(Event.tag, HandshakeAck.class, 1, LinkEventType.HandshakeAck);
    }

    public HandshakeAck() {
        super(tag.getNumProps());
        init();
    }

    protected HandshakeAck(int length) {
        super(length + tag.getNumProps());
        init();
    }

    private void init() {
        result_ = false;
    }

    @Override
    protected boolean equalsTo(Cell other) {
        if (!super.equalsTo(other)) {
            return false;
        }
        HandshakeAck o = (HandshakeAck)other;
        if (result_ != o.result_) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode(Fingerprint fingerprint) {
        Hash hash = new Hash(super.hashCode(fingerprint));
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            hash.update(result_);
        }
        return hash.code();
    }

    @Override
    protected boolean isEquivalent(Cell other, Fingerprint fingerprint) {
        if (!super.isEquivalent(other, fingerprint)) {
            return false;
        }
        HandshakeAck o = (HandshakeAck)other;
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            if (result_ != o.result_) {
                return false;
            }
        }
        return true;
    }

    @Override
    public Cell.Tag _getTypeTag() { return tag; }

    @Override
    public int _getTypeId() { return tag.getTypeId(); }

    @Override
    protected void describe(StringBuilder sb) {
        super.describe(sb);
        sb.append(" Result: ");
        sb.append(result_);
    }

    // Serialization

    @Override
    public void deserialize(Deserializer deserializer) throws IOException {
        super.deserialize(deserializer);
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            result_ = deserializer.readBoolean();
        }
    }

    @Override
    public int length() {
        int length = super.length();
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            length += Serializer.lengthBoolean(result_);
        }
        return length;
    }

    @Override
    public void serialize(Serializer serializer) {
        super.serialize(serializer);
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            serializer.writeBoolean(result_);
        }
    }
}
