// auto-generated by x2java xpiler

package x2java;

import java.io.IOException;
import java.util.*;

import x2java.*;
import x2java.util.*;

public class LinkSessionConnected extends Event {
    protected static Tag tag;

    private String linkName_;
    private boolean result_;
    private Object context_;

    public String getLinkName() {
        return linkName_;
    }
    public LinkSessionConnected setLinkName(String value) {
        fingerprint.touch(tag.getOffset() + 0);
        linkName_ = value;
        return this;
    }

    public boolean getResult() {
        return result_;
    }
    public LinkSessionConnected setResult(boolean value) {
        fingerprint.touch(tag.getOffset() + 1);
        result_ = value;
        return this;
    }

    public Object getContext() {
        return context_;
    }
    public LinkSessionConnected setContext(Object value) {
        fingerprint.touch(tag.getOffset() + 2);
        context_ = value;
        return this;
    }

    static {
        tag = new Tag(Event.tag, LinkSessionConnected.class, 3, LinkEventType.LinkSessionConnected);
    }

    public LinkSessionConnected() {
        super(tag.getNumProps());
    }

    protected LinkSessionConnected(int length) {
        super(length + tag.getNumProps());
    }

    @Override
    protected boolean equalsTo(Cell other) {
        if (!super.equalsTo(other)) {
            return false;
        }
        LinkSessionConnected o = (LinkSessionConnected)other;
        if (linkName_ != o.linkName_) {
            return false;
        }
        if (result_ != o.result_) {
            return false;
        }
        if (context_ != o.context_) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode(Fingerprint fingerprint) {
        Hash hash = new Hash(super.hashCode(fingerprint));
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            hash.update(linkName_);
        }
        if (touched.get(1)) {
            hash.update(result_);
        }
        if (touched.get(2)) {
            hash.update(context_);
        }
        return hash.code();
    }

    @Override
    protected boolean isEquivalent(Cell other, Fingerprint fingerprint) {
        if (!super.isEquivalent(other, fingerprint)) {
            return false;
        }
        LinkSessionConnected o = (LinkSessionConnected)other;
        Capo touched = fingerprint.capo(tag.getOffset());
        if (touched.get(0)) {
            if (linkName_ != o.linkName_) {
                return false;
            }
        }
        if (touched.get(1)) {
            if (result_ != o.result_) {
                return false;
            }
        }
        if (touched.get(2)) {
            if (context_ != o.context_) {
                return false;
            }
        }
        return true;
    }

    @Override
    public Cell.Tag _getTypeTag() { return tag; }

    @Override
    public int _getTypeId() { return tag.getTypeId(); }

    @Override
    protected void describe(StringBuilder sb) {
        super.describe(sb);
        sb.append(" LinkName: ");
        sb.append(linkName_);
        sb.append(", Result: ");
        sb.append(result_);
        sb.append(", Context: ");
        sb.append(context_);
    }
}
